# Generated by Django 4.0.6 on 2022-07-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('Undone', 'Undone'), ('Done', 'Done')], max_length=6),
        ),
    ]
